# Generated by Django 3.2.6 on 2021-08-25 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField(verbose_name='Height in inches')),
                ('weight', models.IntegerField(verbose_name='Weight in lbs')),
                ('goal_weight', models.IntegerField(verbose_name='Goal weight in lbs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protein', models.IntegerField(verbose_name='Protein in grams')),
                ('carbs', models.IntegerField(verbose_name='Carbs in grams')),
                ('fat', models.IntegerField(verbose_name='Fat in grams')),
                ('sugar', models.IntegerField(verbose_name='Sugar in grams')),
                ('calories', models.IntegerField()),
                ('sodium', models.IntegerField(verbose_name='Sodium in milligrams')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.IntegerField(verbose_name='Duration in minutes')),
                ('calories_burned', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
